name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Bump Homebrew Cask
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Homebrew Cask
        uses: mislav/bump-homebrew-formula-action@v4
        with:
          # The name of the cask file to update
          formula-name: clutch
          formula-path: Casks/clutch.rb
          # The repository where the tap lives
          homebrew-tap: shitz/homebrew-clutch
          # The path to the file inside the tap repo
          base-branch: main
          download-url: https://github.com/shitz/clutch/releases/download/${{ github.event.release.tag_name }}/Clutch_${{ github.event.release.tag_name }}_aarch64.dmg
        env:
          # You must create a PAT with 'repo' scope and add it to your Secrets
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
